// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"900","screenHeight":"630","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"OrangeLighting","status":false,"description":"Lighting system <OrangeLighting>","parameters":{"lightMaskSwitch":"0","opacityVariable":"100","tintSpeed":"0.3","defaultMaskColor":"black"}},
{"name":"YEP_AnimateTilesOption","status":true,"description":"v1.01 Because some computers and devices lag with animated\ntiles on the map, an option is added to disable them.","parameters":{"Command Name":"Animated Tiles","Default Setting":"auto"}}
];
